#!/bin/bash

# SPIR-V Validation Script
# This script validates SPIR-V binaries generated by the VKML compiler using spirv-val

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Script directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Default values
SPIRV_FILE=""
TARGET_ENV="vulkan1.0"
VERBOSE=false
INSTALL_TOOLS=false

print_usage() {
    cat << EOF
Usage: $0 [OPTIONS] <spirv_file>

Validates SPIR-V binary files using spirv-val.

OPTIONS:
    -h, --help              Show this help message
    -v, --verbose           Enable verbose output
    -t, --target-env ENV    Target environment (default: vulkan1.0)
                           Options: vulkan1.0, vulkan1.1, vulkan1.2, vulkan1.3,
                                   spv1.0, spv1.1, spv1.2, spv1.3, spv1.4, spv1.5, spv1.6
    -i, --install          Install spirv-tools if not found
    
EXAMPLES:
    # Validate a SPIR-V file for Vulkan 1.2
    $0 -t vulkan1.2 shader.spv
    
    # Validate with verbose output
    $0 -v shader.spv
    
    # Install spirv-tools and validate
    $0 -i shader.spv

EOF
}

install_spirv_tools() {
    echo -e "${YELLOW}Installing SPIR-V Tools...${NC}"
    
    if command -v apt-get &> /dev/null; then
        echo "Using apt-get to install spirv-tools..."
        sudo apt-get update
        sudo apt-get install -y spirv-tools
    elif command -v yum &> /dev/null; then
        echo "Using yum to install spirv-tools..."
        sudo yum install -y spirv-tools
    elif command -v brew &> /dev/null; then
        echo "Using Homebrew to install spirv-tools..."
        brew install spirv-tools
    else
        echo -e "${RED}Error: No supported package manager found.${NC}"
        echo "Please install SPIR-V Tools manually from:"
        echo "https://github.com/KhronosGroup/SPIRV-Tools"
        exit 1
    fi
    
    if command -v spirv-val &> /dev/null; then
        echo -e "${GREEN}SPIR-V Tools installed successfully!${NC}"
    else
        echo -e "${RED}Error: Failed to install SPIR-V Tools.${NC}"
        exit 1
    fi
}

check_spirv_val() {
    if ! command -v spirv-val &> /dev/null; then
        echo -e "${RED}Error: spirv-val not found in PATH${NC}"
        echo ""
        echo "Please install SPIR-V Tools:"
        echo "  Ubuntu/Debian: sudo apt-get install spirv-tools"
        echo "  Fedora/RHEL:   sudo yum install spirv-tools"
        echo "  macOS:         brew install spirv-tools"
        echo ""
        echo "Or use the -i flag to attempt automatic installation."
        exit 1
    fi
}

validate_spirv() {
    local spirv_file="$1"
    local target_env="$2"
    local verbose=$3
    
    if [ ! -f "$spirv_file" ]; then
        echo -e "${RED}Error: File not found: $spirv_file${NC}"
        exit 1
    fi
    
    echo -e "${YELLOW}Validating SPIR-V file: $spirv_file${NC}"
    echo "Target environment: $target_env"
    echo ""
    
    local cmd="spirv-val --target-env $target_env"
    
    if [ "$verbose" = true ]; then
        echo "Running: $cmd $spirv_file"
        echo ""
    fi
    
    if $cmd "$spirv_file"; then
        echo ""
        echo -e "${GREEN}✓ SPIR-V validation PASSED${NC}"
        return 0
    else
        echo ""
        echo -e "${RED}✗ SPIR-V validation FAILED${NC}"
        return 1
    fi
}

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -h|--help)
            print_usage
            exit 0
            ;;
        -v|--verbose)
            VERBOSE=true
            shift
            ;;
        -t|--target-env)
            TARGET_ENV="$2"
            shift 2
            ;;
        -i|--install)
            INSTALL_TOOLS=true
            shift
            ;;
        -*)
            echo -e "${RED}Error: Unknown option: $1${NC}"
            print_usage
            exit 1
            ;;
        *)
            SPIRV_FILE="$1"
            shift
            ;;
    esac
done

# Check if SPIR-V file was provided
if [ -z "$SPIRV_FILE" ]; then
    echo -e "${RED}Error: No SPIR-V file specified${NC}"
    print_usage
    exit 1
fi

# Install tools if requested
if [ "$INSTALL_TOOLS" = true ]; then
    install_spirv_tools
fi

# Check if spirv-val is available
check_spirv_val

# Validate the SPIR-V file
validate_spirv "$SPIRV_FILE" "$TARGET_ENV" "$VERBOSE"
