#!/usr/bin/env python3
"""
SPIR-V Validation Script
This script validates SPIR-V binaries generated by the VKML compiler using spirv-val
"""

import argparse
import os
import subprocess
import sys
from pathlib import Path

# ANSI color codes
RED = '\033[0;31m'
GREEN = '\033[0;32m'
YELLOW = '\033[1;33m'
NC = '\033[0m'  # No Color


def print_colored(message, color):
    """Print colored message to stdout"""
    if sys.stdout.isatty():
        print(f"{color}{message}{NC}")
    else:
        print(message)


def check_spirv_val():
    """Check if spirv-val is available in PATH"""
    try:
        subprocess.run(['spirv-val', '--version'], 
                      stdout=subprocess.PIPE, 
                      stderr=subprocess.PIPE, 
                      check=True)
        return True
    except (subprocess.CalledProcessError, FileNotFoundError):
        return False


def install_spirv_tools():
    """Attempt to install SPIR-V Tools"""
    print_colored("Installing SPIR-V Tools...", YELLOW)
    
    # Try different package managers
    install_commands = [
        ['sudo', 'apt-get', 'update', '&&', 'sudo', 'apt-get', 'install', '-y', 'spirv-tools'],
        ['sudo', 'yum', 'install', '-y', 'spirv-tools'],
        ['brew', 'install', 'spirv-tools'],
    ]
    
    for cmd in install_commands:
        try:
            subprocess.run(cmd, check=True)
            if check_spirv_val():
                print_colored("SPIR-V Tools installed successfully!", GREEN)
                return True
        except (subprocess.CalledProcessError, FileNotFoundError):
            continue
    
    print_colored("Error: Failed to install SPIR-V Tools.", RED)
    print("\nPlease install SPIR-V Tools manually from:")
    print("https://github.com/KhronosGroup/SPIRV-Tools")
    print("\nInstallation commands:")
    print("  Ubuntu/Debian: sudo apt-get install spirv-tools")
    print("  Fedora/RHEL:   sudo yum install spirv-tools")
    print("  macOS:         brew install spirv-tools")
    return False


def validate_spirv(spirv_file, target_env='vulkan1.0', verbose=False):
    """Validate a SPIR-V binary file"""
    spirv_path = Path(spirv_file)
    
    if not spirv_path.exists():
        print_colored(f"Error: File not found: {spirv_file}", RED)
        return False
    
    print_colored(f"Validating SPIR-V file: {spirv_file}", YELLOW)
    print(f"Target environment: {target_env}")
    print()
    
    cmd = ['spirv-val', '--target-env', target_env, str(spirv_path)]
    
    if verbose:
        print(f"Running: {' '.join(cmd)}")
        print()
    
    try:
        result = subprocess.run(cmd, 
                              capture_output=True, 
                              text=True, 
                              check=False)
        
        if result.stdout:
            print(result.stdout)
        if result.stderr:
            print(result.stderr, file=sys.stderr)
        
        if result.returncode == 0:
            print()
            print_colored("✓ SPIR-V validation PASSED", GREEN)
            return True
        else:
            print()
            print_colored("✗ SPIR-V validation FAILED", RED)
            return False
            
    except Exception as e:
        print_colored(f"Error running spirv-val: {e}", RED)
        return False


def main():
    parser = argparse.ArgumentParser(
        description='Validate SPIR-V binary files using spirv-val',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Validate a SPIR-V file for Vulkan 1.2
  %(prog)s -t vulkan1.2 shader.spv
  
  # Validate with verbose output
  %(prog)s -v shader.spv
  
  # Install spirv-tools and validate
  %(prog)s -i shader.spv
        """
    )
    
    parser.add_argument('spirv_file', 
                       help='SPIR-V binary file to validate')
    parser.add_argument('-v', '--verbose', 
                       action='store_true',
                       help='Enable verbose output')
    parser.add_argument('-t', '--target-env', 
                       default='vulkan1.0',
                       choices=['vulkan1.0', 'vulkan1.1', 'vulkan1.2', 'vulkan1.3',
                               'spv1.0', 'spv1.1', 'spv1.2', 'spv1.3', 
                               'spv1.4', 'spv1.5', 'spv1.6'],
                       help='Target environment (default: vulkan1.0)')
    parser.add_argument('-i', '--install', 
                       action='store_true',
                       help='Install spirv-tools if not found')
    
    args = parser.parse_args()
    
    # Install tools if requested
    if args.install:
        if not install_spirv_tools():
            return 1
    
    # Check if spirv-val is available
    if not check_spirv_val():
        print_colored("Error: spirv-val not found in PATH", RED)
        print()
        print("Please install SPIR-V Tools:")
        print("  Ubuntu/Debian: sudo apt-get install spirv-tools")
        print("  Fedora/RHEL:   sudo yum install spirv-tools")
        print("  macOS:         brew install spirv-tools")
        print()
        print("Or use the -i flag to attempt automatic installation.")
        return 1
    
    # Validate the SPIR-V file
    success = validate_spirv(args.spirv_file, args.target_env, args.verbose)
    return 0 if success else 1


if __name__ == '__main__':
    sys.exit(main())
